-- AlterEnum
BEGIN;
CREATE TYPE "NodeType_new" AS ENUM ('INITIAL', 'MANUAL_TRIGGER', 'HTTP_REQUEST', 'GOOGLE_FORM_TRIGGER', 'TYPEFORM_TRIGGER', 'GMAIL_TRIGGER', 'GOOGLE_SHEETS_TRIGGER', 'INSTAGRAM_COMMENT_TRIGGER', 'INSTAGRAM_REPLY_COMMENT', 'YOUTUBE_COMMENT_TRIGGER', 'YOUTUBE_REPLY_COMMENT', 'AI_REPLY_GENERATOR', 'AI_TEXT', 'ANTHROPIC', 'CONDITION', 'GEMINI', 'OPENAI', 'DISCORD', 'SLACK', 'NOTION_ACTION', 'TELEGRAM_ACTION', 'TELEGRAM_TRIGGER', 'WHATSAPP_ACTION', 'GMAIL_ACTION', 'GOOGLE_SHEETS_ACTION');
ALTER TABLE "Node" ALTER COLUMN "type" TYPE "NodeType_new" USING ("type"::text::"NodeType_new");
ALTER TYPE "NodeType" RENAME TO "NodeType_old";
ALTER TYPE "NodeType_new" RENAME TO "NodeType";
DROP TYPE "public"."NodeType_old";
COMMIT;

