-- ============================================================================
-- Self-hosted execution runtime, part 1: the queue and the durable step store.
--
-- Additive only. Nothing reads any of this yet: `Workflow.executionRuntime` is
-- NULL for every existing row, and NULL means "run this workflow on Inngest",
-- which is exactly what happens today. Full design:
-- plans/PART1-QUEUE-AND-WORKER.md
--
-- ⚠️ THIS FILE IS HAND-EDITED. The partial unique index at the bottom cannot be
-- expressed in Prisma's schema DSL, so it exists ONLY here. Prisma will not
-- drift-detect it and it will never appear in schema.prisma — if this migration
-- is ever regenerated, that index must be re-added by hand or the per-workflow
-- concurrency guarantee silently disappears.
-- ============================================================================

-- CreateEnum
CREATE TYPE "JobStatus" AS ENUM ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED');

-- AlterTable
ALTER TABLE "Workflow" ADD COLUMN     "executionRuntime" TEXT;

-- CreateTable
CREATE TABLE "WorkflowJob" (
    "id" TEXT NOT NULL,
    "workflowId" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "idempotencyKey" TEXT,
    "status" "JobStatus" NOT NULL DEFAULT 'PENDING',
    "runAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "reclaims" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL,
    "lockedBy" TEXT,
    "leaseExpiresAt" TIMESTAMP(3),
    "executionId" TEXT,
    "lastError" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WorkflowJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StepResult" (
    "executionId" TEXT NOT NULL,
    "stepId" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StepResult_pkey" PRIMARY KEY ("executionId","stepId")
);

-- CreateIndex
CREATE UNIQUE INDEX "WorkflowJob_executionId_key" ON "WorkflowJob"("executionId");

-- CreateIndex
CREATE INDEX "WorkflowJob_status_runAt_idx" ON "WorkflowJob"("status", "runAt");

-- CreateIndex
CREATE INDEX "WorkflowJob_workflowId_status_idx" ON "WorkflowJob"("workflowId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "WorkflowJob_workflowId_idempotencyKey_key" ON "WorkflowJob"("workflowId", "idempotencyKey");

-- AddForeignKey
ALTER TABLE "WorkflowJob" ADD CONSTRAINT "WorkflowJob_workflowId_fkey" FOREIGN KEY ("workflowId") REFERENCES "Workflow"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StepResult" ADD CONSTRAINT "StepResult_executionId_fkey" FOREIGN KEY ("executionId") REFERENCES "Execution"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================================
-- HAND-WRITTEN BELOW THIS LINE — not generated by Prisma, not in schema.prisma.
-- ============================================================================

-- The per-workflow concurrency guarantee.
--
-- This one index is what replaces Inngest's
--   concurrency: { key: "event.data.workflowId", limit: 1 }
-- and it is load-bearing for correctness, not throughput: two runs of one
-- workflow in flight together race on shared external state (the same
-- spreadsheet, the same inbox) and break fan-out item ordering.
--
-- It is a ROW CONSTRAINT rather than a lock on purpose. `pg_advisory_lock` is
-- session-scoped, and PgBouncer in transaction mode hands the underlying session
-- to another client between statements — so on Neon's pooled endpoint (which is
-- what DATABASE_URL points at) a session lock is neither reliably held by nor
-- releasable by the process that took it. Postgres enforcing a uniqueness rule
-- depends on none of that.
--
-- The worker's claim query also filters with NOT EXISTS(... status='RUNNING'),
-- but that filter is only a fast path: FOR UPDATE SKIP LOCKED lets two workers
-- select two DIFFERENT pending jobs of the same workflow in the same instant,
-- neither seeing the other because neither has flipped to RUNNING yet. This
-- index is what closes that race. The loser's UPDATE raises a unique violation
-- (Prisma P2002), which the worker reads as "that workflow is busy" and retries.
CREATE UNIQUE INDEX "WorkflowJob_one_running_per_workflow"
  ON "WorkflowJob" ("workflowId")
  WHERE status = 'RUNNING';

-- ⚠️ TIER 2 LOOPS — read before implementing them.
--
-- "StepResult" is keyed ("executionId", "stepId") with no iteration counter, so
-- it encodes the same assumption "NodeExecution" and "NodeInputSnapshot" already
-- carry: a node runs AT MOST ONCE per execution. A loops feature must add an
-- iteration ordinal to all THREE tables.
--
-- "StepResult" is the dangerous member of that set. A missing ordinal on the
-- other two produces a visibly wrong or conflicting ROW. Here it produces a
-- silently stale VALUE: iteration 2 of a loop would find iteration 1's memoized
-- step result and return it as its own, with no error anywhere.
